### ISSUE TITLE
Mutiple instantiation of test plan

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-executor#78]
INT-VNV

![Capture](https://user-images.githubusercontent.com/16242967/70423257-7088ea80-1a6d-11ea-94fa-3132dee60853.PNG)

Running a test the number of instantiation is double than expected

**Comment by tblanco219** [comment]
Between 09:18:00 and 09:19:00 there are no calls to the executor platform, because the test fails in PA with the following error:
**Wrong JSON from PA: <urllib3.response.HTTPResponse object at 0x7f93bae96b00>, exception: Expecting value: line 1 column 1 (char 0)**

In the planner database, only one test is located at 09:18:26 with an error status.
